### PR TITLE
Move tickheight file from cmssw

### PR DESCRIPTION
**Pull request by mmusich**
First push of the repository, needed for https://github.com/cms-sw/cmssw/pull/37066

### CODE REVIEW

**Comment by tvami** [comment]
assign alca

**Comment by qliphy** [comment]
tested with https://github.com/cms-sw/cmssw/pull/37066

**Comment by qliphy** [comment]
+1

**Comment by tvami** [comment]
+db

**Comment by mmusich** [comment]
@smuzaffar @qliphy @perrotta 
now that cms-sw/cmssw#37066 is merged this one should be as well, otherwise unit tests will start failing.

**Comment by smuzaffar** [comment]
+externals

**Pull request merged**
