### PR TITLE
add `DefectsFromConstructionDB.dat` to `CondTools/SiStrip` data repo

### PR DESCRIPTION
**Pull request by mmusich**
Title says it all, moved from `cmssw/CalibTracker/SiStripQuality`.

### CODE REVIEW

**Comment by mmusich** [comment]
needed for https://github.com/cms-sw/cmssw/pull/37120.

**Comment by mmusich** [comment]
please test

**Comment by tvami** [comment]
+1

**Comment by qliphy** [comment]
+1

**Comment by qliphy** [comment]
merge

**Pull request merged**
